<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<style type="text/css">
#wrapper{
word-wrap: break-word;
font-family: sans-serif;
font-size: 98%;
font-style: italic;

text-align: auto;
       width: 1060px;
        height:1200000px;
        background: url("/manuales/fabric_plaid.png") repeat;
        -webkit-box-shadow: 0 0 1px rgba(0,0,0,.2);
        -moz-box-shadow: 0 0 0px rgba(0,0,0,.2);
        box-shadow: 0 0 0px rgba(0,0,0,.2);
padding: 5px;

}


<img src="" width="600" height="300" /></a>
</style>

<font color="red"></font>

<div id="wrapper" class="clearfix">
<pre>  <h3>
<font color="red"></font>
<font color="blue"></font>
<u></u>
<font size="6"></font>
<font size="6" color="red">Compiling a kernel on Centos - Suse - Ubuntu (Guide compilation from several sources)</FONT>

tecmint manual

# cd /usr/src/
# wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.17.11.tar.xz
# tar -xvf linux-4.17.11.tar.xz
# cd linux-decompressed
to mantain same configuration from previous kernel compilation copy the /boot/.config to /usr/src directory
if you decide not to copy the /boot/.config execute the make menuconfig  to generate a new one
# make menuconfig
# make bzImage
# make modules
# make
# make install
# make modules_install


The Geek Stuff manual
# cd /usr/src/
# wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.17.11.tar.xz
# tar -xvJf linux-4.17.11.tar.xz
# make menuconfig
# make                     compile the main kernel
# make modules             Compile the kernel modules
# make modules_install     At this point we should see a directory named /lib/modules/4.17.11/ in the system
# make install             this will install the following lines in the /boot directory
	                   vmlinuz-4.17.11,      The actual kernel
                           System.map-4.17.11    The symbols exported by the kernel,This file contains pointers to functions 
                                                  in the kernel and is used for debugging kernel problems
              		   initrd.img-4.17.11    initr image is a temporay root file system used during boot process
  			   config-4.17.11        kernel configuration file generated by using make menuconfig
			   make install          instruction also update the grub.cfg by default

<font color="red">Additional Linux Kernel configuration make targets</font>

mrproper                   Removes old configuration and temporary files.
oldconfig                  Updates an old configuration file, updating only those items that are new.
silentoldconfig            Similar to oldconfig but reduces screen clutter.
defconfig                  Creates a configuration file using default values for your platform.
allmodconfig               Creates a configuration file that uses modular configuration as much as possible.
config                     Configures every item in the kernel using a text-based interface. Sluggish and impractical with modern kernels.
menuconfig                 Configures the kernel using a text-based menu system. Adequate when using a text-based console.
xconfig                    Similar to menuconfig, but configuration is done using a Qt-based GUI environment.
gconfig                    Similar to xconfig but uses a GTK-based GUI environment.
